language: python
python:
  - '3.7'
cache: pip
install:
  - pip install -e .[testing]
  - pip install -e .[docs]
script:
  - py.test --cov-report term-missing --cov app -v
  - cd docs; sphinx-build -nWT -b dummy . _build/html